### ISSUE TITLE
Use upstream nixpkgs

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/iohk-nix#101]
It would be nice not to have our own fork of nixpkgs.

As far as I know, there are a few things preventing us from using upstream:
- Changes to the GHC expressions
    - I *think* @angerman has a plan to move these out to `haskell.nix` eventually so we don't depend on the nixpkgs versions any more, which would solve this.
- The "split tests" patch
   - Obsoleted by `haskell.nix`
- The stdenv metrics patch
   - https://github.com/NixOS/nixpkgs/pull/45744 has stalled a bit but it didn't look like people were completely opposed to it, so probably we could get it in with a bit more work.

Am I missing anything?

**Comment by rvl** [comment]
> Am I missing anything?

I think there is also a stdenv change for cross-compiling - @angerman ?

> It would be nice not to have our own fork of nixpkgs.

I think we should differentiate between stdenv and non-stdenv changes.

1. The impact of having a fork with non-stdenv changes is the maintenance cost to us, and having upstream not benefit from our work.
2. The impact of having a fork with stdenv changes is felt by users.
    - Using the IOHK binary cache becomes mandatory, or else users will really "rebuild the world" - not just GHC and haskell packages. They also have no way of using the NixOS binary cache, but building all IOHK stuff from source.
   - We need to be careful to ensure all programs which might be used by developers get built and cached by IOHK Hydra.
   - There is also no opportunity for sharing of derivations between the user's base system and IOHK packages (something that would be possible if we built off the stable channel and the user's system was on the stable channel).

> The stdenv metrics patch

With the phase metrics, are we actually using the results of that? Does anyone know where to view the metrics? @disassembler

**Comment by disassembler** [comment]
We lost the phase metrics output with haskell.nix, so there's really no reason to keep it. I'm all for switching to upstream nixpkgs. You can still see the metrics on plutus: https://hydra.iohk.io/build/1011125#tabs-details

**Comment by angerman** [comment]
I'm currently working on input-output-hk/haskell.nix#210, which should allow us to use haskell.nix with upstream nixpkgs. I'm facing some issues (specifically building a mingw32 cross gcc) with the release. Thanks @rvl for the ping.

**Comment by michaelpj** [comment]
I do actually quite like the metrics. Did we give up on upstreaming that patch (https://github.com/NixOS/nixpkgs/pull/45744)? 

Presumably if `haskell.nix` isn't using `stdenv` then we could add metrics there ourselves without having to worry about upstream nixpkgs.

I guess this is probably a prerequisite for updating our nixpkgs to the next stable, given that otherwise we have to port all of our patches over, which would be annoying.

**Comment by angerman** [comment]
> I do actually quite like the metrics. Did we give up on upstreaming that patch ([NixOS/nixpkgs#45744](https://github.com/NixOS/nixpkgs/pull/45744))?
> 
> Presumably if `haskell.nix` isn't using `stdenv` then we could add metrics there ourselves without having to worry about upstream nixpkgs.
> 
> I guess this is probably a prerequisite for updating our nixpkgs to the next stable, given that otherwise we have to port all of our patches over, which would be annoying.

It *is* using `stdenv`, however you end up getting that for *every* component not per package.
