### ISSUE TITLE
Missing pkg-config on some buildkite machines

### ISSUE THREAD

**Issue by erikd** [input-output-hk/iohk-nix#112]
Failure is on PR : https://github.com/input-output-hk/cardano-shell/pull/202

Build kite log : https://buildkite.com/input-output-hk/cardano-shell/builds/697#2680a4c8-a22f-4866-9aa8-a0a71a561445

```
Process exited with code: ExitFailure 1
Logs have been written to: /var/lib/buildkite-agent/builds/buildkite-packet-3/input-output-hk/cardano-shell/.stack-work/logs/libsystemd-journal-1.4.4.log
 
Configuring libsystemd-journal-1.4.4...
Cabal-simple_mPHDZzAJ_2.4.1.0_ghc-8.6.5: The program 'pkg-config' version >=0.9.0 is required but it could not be found.
```

**Comment by jbgi** [comment]
This PR should fix the issue: https://github.com/input-output-hk/cardano-shell/pull/204
Can you merge it?
buildkite machines are running nixos so using stack with nix support is required for stack to find system dependencies.

**Comment by erikd** [comment]
PR approved. Will merge once CI is green

**Comment by erikd** [comment]
Ok, my PR builds. Closing this. Thanks @jbgi !
