### ISSUE TITLE
Always give a custom error when a non-statically known attribute is accessed

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/iohk-nix#117]
Many of the gotchas in [gotcha 2](https://github.com/input-output-hk/iohk-nix/blob/master/gotchas/gotcha-2.md) are signalled by "attribute missing" errors. We could significantly improve the UX there (and hopefully not need separate documentation!) by throwing a custom error in those places.

For example, consider the stackage resolver. At the moment if you try and use a resolver that isn't in the current `stackage.nix`, you get an unhelpful error, but we can easily change that:
```diff
       let
         # The Stackage release referenced in the stack config
-        pkg-def = stackage.${stack-pkgs.resolver};
+        pkg-def = stackage.${stack-pkgs.resolver} or throw 
+          "This version of stackage.nix does not know about the Stackage resolver ${stack-pkgs.resolver}, you may need to update haskell.nix to one that includes a newer stackage.nix.";
         # The compiler referenced in the stack config
         compiler = (stack-pkgs.extras hackage).compiler or (pkg-def hackage).compiler;
         patchesModule = ghcHackagePatches.${compiler.nix-name} or {};
```
(I'll open a PR for this one if people like the idea.)

I think there's a pattern here: any time we access an attribute that we don't know *statically* will be present, we should do `or throw <msg>`. Otherwise we're doing the equivalent of `fromJust $ lookup name attrset`.

At least I think we could do this for some of the common cases in the gotchas. And if a user reports an "attribute missing" error and it's not them screwing up, then we should probably add a custom error.

**Comment by jbgi** [comment]
great idea!

**Comment by michaelpj** [comment]
https://github.com/input-output-hk/haskell.nix/pull/194

**Comment by michaelpj** [comment]
I think there's also a bunch of places in the generated nix from `nix-tools` that could do with something like this, but I'm not sure where.

**Comment by disassembler** [comment]
closing in favor of https://github.com/input-output-hk/haskell.nix/pull/194 as this would need implemented in haskell.nix/stackage.nix

**Comment by michaelpj** [comment]
Well, this was supposed to cover the general problem. We do this in a bunch of places (probably in `iohk-nix` too. And that PR doesn't fix the entire problem, so it would be nice to have a tracking issue too.

**Comment by rvl** [comment]
There is also an iohk-nix side to this. If the user updates the LTS version in a cardano project and gets a message "update your haskell.nix", what should they do. They should actually update iohk-nix.

So thankfully we can remove the complicated "missing attribute" documentation and replace it with:
0. If you change stackage snapshot or compiler, you may need a newer iohk-nix version.
1. to update haskell.nix, update the iohk-nix pin.
2. to update the iohk-nix, do ...

**Comment by rvl** [comment]
Also related: input-output-hk/haskell.nix#125.

**Comment by michaelpj** [comment]
We shouldn't give an error that mentions `iohk-nix` from `haskell.nix`, some non IOHK folks are using `haskell.nix` too.

**Comment by michaelpj** [comment]
Reopening since I think there's more to do here.

**Comment by angerman** [comment]
> We shouldn't give an error that mentions `iohk-nix` from `haskell.nix`, some non IOHK folks are using `haskell.nix` too.

On that note, the cut between `haskell.nix` and `iohk-nix` is pretty much along the "toolbox" and "end user library". Should it stay that way or do we have really useful abstractions in iohk-nix that should be moved into haskell.nix?  From the top of my head that would mostly be the cross compilation setup logic we have, as it's somewhat awkward to point people to iohk-nix if they want to use haskell.nix to cross compile stuff.

**Comment by michaelpj** [comment]
:+1: on moving some Haskell-specific stuff to `haskell.nix`. TBH I find `iohk-nix` and `haskell.nix` a bit annoyingly coupled at the moment.
