### ISSUE TITLE
CI job that autoupdates the cabal.project file

### ISSUE THREAD

**Issue by erikd** [input-output-hk/iohk-nix#127]
The [cardano-repo-tool](input-output-hk/cardano-repo-tool) has a featrue where it can update the git hashes in the `cabal.project` file, from the `stack.yaml` file.

It would be nice to have this as a CI job. Basically:

* Run `cardano-repo-tool update-cabal-project` in the top level directory.
* If the `cabal.project` file changes,
  - Fail the build
  - Provide a diff of the change as an artifact.

**Comment by dnadales** [comment]
As starting point we could use the [setup in `cardano-ledger`](https://github.com/input-output-hk/cardano-ledger/blob/677b9377d4dc541eb3d7ffac079bdab7d489df1f/.buildkite/pipeline.yml#L27).
