### ISSUE TITLE
check-hydra script fails if auto-gc occurs during build

### ISSUE THREAD

**Issue by rvl** [input-output-hk/iohk-nix#139]
The [check-hydra script fails](https://buildkite.com/input-output-hk/cardano-wallet/builds/741#1c48f64b-bb11-4c8d-95b1-903dcabbb6d5) sometimes, and succeeds when retried.

The message is:
```
warning: `--gc-roots-dir' not specified
restarting hydra-eval-jobs after job 'native.benchmarks.cardano-wallet-core.db.x86_64-linux' because heap size is at 1317535744 bytes
warning: `--gc-roots-dir' not specified
restarting hydra-eval-jobs after job 'native.benchmarks.cardano-wallet-http-bridge.restore.x86_64-linux' because heap size is at 1292369920 bytes
warning: `--gc-roots-dir' not specified
restarting hydra-eval-jobs after job 'native.cardano-wallet-http-bridge.x86_64-linux' because heap size is at 1401421824 bytes
warning: `--gc-roots-dir' not specified
error: getting status of '/nix/store/rar9fy1a12axkdjadksqbgj7b8sz9cf6-hackage-exprs-source': No such file or directory
ERROR: Failed to evaluate release.nix
```

It looks like something got GC'd while the check-hydra script was running.

Eval-time dependencies aren't GC rooted correctly, because nix assumes evals are fast and GCs don't happen often. But with the auto-gc, an eval can trigger a GC, and break itself.

The check-hydra script should ensure that eval-time dependencies are GC rooted. It should also not print confusing warning messages.

**Comment by disassembler** [comment]
While it would be great to get that fixed, check-hydra is just a wrapper around hydra-eval-jobs, which would require an upstream fix. We'll leave this open as a reminder to get to it when we start looking at improving hydra, but there's nothing we can do about it in the short term.
