### ISSUE TITLE
Switch from `stack-hpc-coveralls` to `hpc-coveralls`

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/iohk-nix#252]
# Problem

The `stack-rebuild` job is the longest in CI -- and by far.

# Options

## Plan A, conservative

As @rvl suggested in, we should look into replicating the setup in https://github.com/input-output-hk/iohk-nix/tree/master/skeleton/.buildkite, to enable caching of Stack builds -- and this should make the build very fast.

## Plan B, drastic

We only _really_ need the `stack-rebuild` job because of coveralls, which we currently do [1,2] via http://hackage.haskell.org/package/stack-hpc-coveralls -- which can't work well in Nix context.

It is true that Stack users are dependent on maintaining the Stack-buildability, but that maintenance can be done asynchronously -- adding fixes after the fact.  And one would think that such issues (that is Stack failing, with Nix builds succeeding) should happen quite rarely, anyway -- after all, Stack is used as source for Nix definitions, so it's implicitly always used, in some sense.

So if plan A fails to satisfy our performance goals, we should look into:

1. Switching to a pure derivation based on http://hackage.haskell.org/package/hpc-coveralls.
2. Making the `stack rebuild` job non-mandatory.

--
1. https://github.com/input-output-hk/cardano-node/blob/master/scripts/buildkite/rebuild.hs#L51
2. https://github.com/input-output-hk/cardano-node/blob/master/scripts/buildkite/stack-hpc-coveralls.nix

**Comment by rvl** [comment]
`cardano-node` is not using the stack caching which has been added to the [skeleton reference project](https://github.com/input-output-hk/iohk-nix/tree/master/skeleton), so no surprise that it takes a loong time to build.

In any case, if the stack build is something relied upon by developers, you want it running in CI to ensure that people's builds don't get broken.

So I would suggest copying the example from skeleton first.

**Comment by deepfire** [comment]
@rvl, do you think that making this BK check non-mandatory would make sense, by the way?

**Comment by rvl** [comment]
Note that any non-mandatory CI check is doomed to be ignored by people who want to merge their PR.

If a broken stack build reaches master, and some developers need stack builds, then it's too late.

And we are still paying for the machine time consumed by the build.

With the stack caching enabled, this Buildkite step is likely to have built and run tests before the Hydra build has finished.

**Comment by deepfire** [comment]
So with what you said, yes, I agree, we definitely should look into caching first..

**Comment by deepfire** [comment]
@rvl, updated the plan.
