### ISSUE TITLE
Lost functionality

### ISSUE THREAD

**Issue by angerman** [input-output-hk/iohk-nix#340]
During the haskell.nix migration of plutus (input-output-hk/plutus#1825), at least the following functions went MIA:

- [ ] `getPackges`
- [ ] `stylishHaskell`
- [ ] `haskellPackages`

**Comment by michaelpj** [comment]
Note that we don't particularly care about most of those. Maybe the stylish haskell one.

**Comment by angerman** [comment]
The file is still there https://github.com/input-output-hk/iohk-nix/blob/master/tests/stylish-haskell.nix

It's just not exposed anymore. 🤷‍♂
