### ISSUE TITLE
Using `th-packages`

### ISSUE THREAD

**Issue by nomeata** [input-output-hk/iohk-nix#44]
Previously, I thought I had to patch out uses of TH to get the windows and static build of my project working, but @angerman [said encouraging words](https://github.com/NixOS/nixpkgs/issues/36200#issuecomment-473603955), so I tried to make use of it.

Judging from the comments in some file, I need to add the `iohk-nix` module when I build `pkgs.nix`, which I tried to do here:
https://github.com/entropia/tip-toi-reveng/commit/37d2eb67c8f2b6bccf36625aee787cc88e0f0d02

But it does not work out of the box:
```
~/projekte/tip-toi-reveng $ nix-build -A windows-exe nix
error: The option `packages.remote-iserv.package.license' is used but not defined.
(use '--show-trace' to show detailed location information)
```
and with full trace:
```
~/projekte/tip-toi-reveng $ nix-build -A windows-exe nix --show-trace
error: while evaluating 'tttool-exe' at /home/jojo/projekte/tip-toi-reveng/nix/default.nix:4:16, called from /home/jojo/projekte/tip-toi-reveng/nix/default.nix:44:17:
while evaluating the attribute 'tttool.components.exes.tttool' at undefined position:
while evaluating 'buildComp' at /nix/store/vvy3nghh9n50009j8xlld3jgd45damzy-haskell-lib-source/builder/default.nix:77:28, called from undefined position:
while evaluating anonymous function at /nix/store/vvy3nghh9n50009j8xlld3jgd45damzy-haskell-lib-source/builder/comp-builder.nix:3:1, called from /nix/store/vvy3nghh9n50009j8xlld3jgd45damzy-haskell-lib-source/builder/default.nix:77:39:
while evaluating 'fix' at /nix/store/fm6z30m3jkxg2ycni23aij9zls4nqq3c-source/lib/fixed-points.nix:19:9, called from /nix/store/vvy3nghh9n50009j8xlld3jgd45damzy-haskell-lib-source/builder/comp-builder.nix:195:4:
while evaluating anonymous function at /nix/store/vvy3nghh9n50009j8xlld3jgd45damzy-haskell-lib-source/builder/comp-builder.nix:195:20, called from /nix/store/fm6z30m3jkxg2ycni23aij9zls4nqq3c-source/lib/fixed-points.nix:19:20:
while evaluating 'filterAttrs' at /nix/store/fm6z30m3jkxg2ycni23aij9zls4nqq3c-source/lib/attrsets.nix:115:23, called from /nix/store/vvy3nghh9n50009j8xlld3jgd45damzy-haskell-lib-source/builder/comp-builder.nix:339:4:
while evaluating anonymous function at /nix/store/fm6z30m3jkxg2ycni23aij9zls4nqq3c-source/lib/attrsets.nix:116:29, called from /nix/store/fm6z30m3jkxg2ycni23aij9zls4nqq3c-source/lib/attrsets.nix:116:18:
while evaluating anonymous function at /nix/store/vvy3nghh9n50009j8xlld3jgd45damzy-haskell-lib-source/lib/default.nix:65:39, called from /nix/store/fm6z30m3jkxg2ycni23aij9zls4nqq3c-source/lib/attrsets.nix:116:62:
while evaluating the attribute 'preBuild' at /nix/store/vvy3nghh9n50009j8xlld3jgd45damzy-haskell-lib-source/builder/comp-builder.nix:340:10:
while evaluating anonymous function at /nix/store/fm6z30m3jkxg2ycni23aij9zls4nqq3c-source/lib/modules.nix:75:45, called from undefined position:
while evaluating the attribute 'value' at /nix/store/fm6z30m3jkxg2ycni23aij9zls4nqq3c-source/lib/modules.nix:336:9:
while evaluating the option `packages.tttool.preBuild':
while evaluating the attribute 'isDefined' at /nix/store/fm6z30m3jkxg2ycni23aij9zls4nqq3c-source/lib/modules.nix:374:5:
while evaluating the attribute 'values' at /nix/store/fm6z30m3jkxg2ycni23aij9zls4nqq3c-source/lib/modules.nix:362:9:
while evaluating the attribute 'values' at /nix/store/fm6z30m3jkxg2ycni23aij9zls4nqq3c-source/lib/modules.nix:458:7:
while evaluating anonymous function at /nix/store/fm6z30m3jkxg2ycni23aij9zls4nqq3c-source/lib/modules.nix:348:28, called from /nix/store/fm6z30m3jkxg2ycni23aij9zls4nqq3c-source/lib/modules.nix:348:17:
while evaluating 'dischargeProperties' at /nix/store/fm6z30m3jkxg2ycni23aij9zls4nqq3c-source/lib/modules.nix:416:25, called from /nix/store/fm6z30m3jkxg2ycni23aij9zls4nqq3c-source/lib/modules.nix:349:62:
while evaluating the attribute 'value' at /nix/store/fm6z30m3jkxg2ycni23aij9zls4nqq3c-source/lib/modules.nix:232:58:
while evaluating the attribute 'config.preBuild' at /nix/store/nqciwbgh34f17lw993h99bizqi8l3a58-source/mingw_w64.nix:78:13:
while evaluating 'assertValidity' at /nix/store/fm6z30m3jkxg2ycni23aij9zls4nqq3c-source/pkgs/stdenv/generic/check-meta.nix:234:20, called from /nix/store/fm6z30m3jkxg2ycni23aij9zls4nqq3c-source/pkgs/stdenv/generic/make-derivation.nix:249:18:
while evaluating 'checkValidity' at /nix/store/fm6z30m3jkxg2ycni23aij9zls4nqq3c-source/pkgs/stdenv/generic/check-meta.nix:217:19, called from /nix/store/fm6z30m3jkxg2ycni23aij9zls4nqq3c-source/pkgs/stdenv/generic/check-meta.nix:235:18:
while evaluating 'hasDeniedUnfreeLicense' at /nix/store/fm6z30m3jkxg2ycni23aij9zls4nqq3c-source/pkgs/stdenv/generic/check-meta.nix:60:28, called from /nix/store/fm6z30m3jkxg2ycni23aij9zls4nqq3c-source/pkgs/stdenv/generic/check-meta.nix:218:8:
while evaluating 'isUnfree' at /nix/store/fm6z30m3jkxg2ycni23aij9zls4nqq3c-source/pkgs/stdenv/generic/check-meta.nix:45:14, called from /nix/store/fm6z30m3jkxg2ycni23aij9zls4nqq3c-source/pkgs/stdenv/generic/check-meta.nix:63:5:
while evaluating 'toList' at /nix/store/fm6z30m3jkxg2ycni23aij9zls4nqq3c-source/lib/lists.nix:222:12, called from /nix/store/fm6z30m3jkxg2ycni23aij9zls4nqq3c-source/pkgs/stdenv/generic/check-meta.nix:63:15:
while evaluating the attribute 'meta.license' at /nix/store/vvy3nghh9n50009j8xlld3jgd45damzy-haskell-lib-source/builder/comp-builder.nix:216:5:
while evaluating the attribute 'license' at undefined position:
while evaluating anonymous function at /nix/store/fm6z30m3jkxg2ycni23aij9zls4nqq3c-source/lib/modules.nix:75:45, called from undefined position:
while evaluating the attribute 'value' at /nix/store/fm6z30m3jkxg2ycni23aij9zls4nqq3c-source/lib/modules.nix:336:9:
while evaluating the option `packages.remote-iserv.package.license':
The option `packages.remote-iserv.package.license' is used but not defined.
```

Is it not possible to just plug the `iohk-module` into a “pure” `haskell.nix` setup?

Also, is there a reason why this template haskell support is not in `haskell.nix` proper?

**Comment by angerman** [comment]
@nomeata this is mostly bleeding edge. The reason being that the iserv-remote logic was just landed a few weeks ago in ghc, but we use it with compilers from 8.4 onwards, hence we have a lot of custom ghc patches.

The libiserv, iserv-remote, and iserv-proxy packages are also thusly not on hackage as they do not really exist for the version we use. They are injected into the build plan through the nix-tools-iohk-overlay (https://github.com/input-output-hk/iohk-nix/blob/master/nix-tools-iohk-overlay.nix) (Soon to be renamed to `extras` instead of `overlay` to prevent confusion with the `overlay` notion in `nix`; see #43).

Sadly we can't generalize the solution for TH yet. The approach we use is similar to the one that GHCJS uses, but it requires an evaluation context for the target. This works fine with WINE when targetting windows, but there is no generic solution (yet?). An alternative approach is the zeroth/evil-splicer approach, which dumps the splices from a host->host compiler and reads them back in.

Why is all this in `iohk-nix` and not in `haskell.nix`? The reason is mostly that this is a very specific application of `haskell.nix`. Whereas `haskell.nix` tries to *only* provide the component level builder. I'm a bit weary on turning haskell.nix into a kitchen sink, even though the boundary between both isn't perfect.

I've also been working on making options inherit properly from a global to package to component level. This should allow for a TH solution that doesn't even need the `th-packages` annotation anymore.

All that said, I'm very happy to see others picking up haskell.nix and will help out as good as I can.

**Comment by nomeata** [comment]
Ok, thanks for the background.

Will `iserv-remove` help with building for Android? Maybe with qemu?

> All that said, I'm very happy to see others picking up haskell.nix and will help out as good as I can.

Judging from https://travis-ci.org/entropia/tip-toi-reveng/jobs/507415166 it seems that somehow the module was already pulled in (via `localLib.iohkNix.getPkgs`) because it complains about doubly-applied patches. But if `localLib.iohkNix.getPkgs` already includes the module, how do I set `th-packages`? I looked at [`default.nix`[(https://github.com/input-output-hk/iohk-nix/blob/master/default.nix), but it does not look like the patch was applied. (Maybe a patch got moved into `haskell.nix` and I am combining incompatible versions of `iohk-nix` and `haskell.nix`? I should investigate that…)

**Comment by angerman** [comment]
`iserv-remote` can in combination with `iserv-proxy` act as iserv, but bridged over a network. This should allow to use TH on any platform for which we have a linker (arm,aarch64,x86_64,ppc?) for ELF and mach-o. I'm not sure if we have a linker for MIPS in the `rts`. That would however include most of the Android targets.

Using `qemu` (maybe even the user mode) would probably work, but I've not tried this. What I did try to was running `iserv-remote` on an android device as well as an iOS device, and then connect to them via `iserv-proxy`; this however involved a fair bit of setup, as launching the remote process can't be trivially automated :-/ And will most likely involve launching the `app` by hand.

There is also an issue with file and process IO.  TH does not provide sufficient information to determine where file and process IO should happen. On the host or on the target.

This is less of an issue with WINE, nodejs, or `qemu` in user mode where the filesystem of the host and target are essentially identical.

The `th-packages` are used by the `iohk-module` to decide which packages need `-fexternal-interpreter` set, and have the `iserv-remote`, `iserv-proxy` setup. 

Usage is here:
https://github.com/input-output-hk/cardano-chain/blob/03cf7207c4961fec6ca22a074759b9cd4014fa06/nix/pkgs.nix#L50-L57

And the relevant definition of the `th-packages` here:
https://github.com/input-output-hk/cardano-chain/blob/03cf7207c4961fec6ca22a074759b9cd4014fa06/nix/pkgs.nix#L13-L20

**Comment by nomeata** [comment]
>  this however involved a fair bit of setup, as launching the remote process can't be trivially automated :-/ And will most likely involve launching the app by hand.

Ok, clearly not a good way for automatic deployment from, say, travis :-)

More cargo-culting from `cardano-chain`, and also passing `iohk-overlay.${compiler}` to `pkg-def-extras` (and manually adding `network` to the plan)  makes the 
```
The option `packages.remote-iserv.package.license' is used but not defined.
```
problem go away (yay!). But I still have the problem that `conduit` seems to be patched twice somehow:
```
building '/nix/store/7xq5j8fqv9z541dg7dkf39fkgbykd7fv-conduit-1.3.1-lib-conduit-x86_64-pc-mingw32.drv'...
unpacking sources
unpacking source archive /nix/store/526cvnsywyjifpkkjmqcsibbfrf0xpqb-conduit-60b3c9a/conduit
source root is conduit
patching sources
applying patch /nix/store/5lfin20d7drxvbsksx73x1xs1k0x4bwn-conduit-1.3.0.2.patch
patching file src/System/Win32File.hsc
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file src/System/Win32File.hsc.rej
builder for '/nix/store/7xq5j8fqv9z541dg7dkf39fkgbykd7fv-conduit-1.3.1-lib-conduit-x86_64-pc-mingw32.drv' failed with exit code 1
```
The version that is being built here, 1.3.1, does not yet have the patch applied upstream (thats from 1.3.1.1). It is also not the version of `conduit` specified in my plan – is it pulled in as a dependency of `iserv-remote` as part of the `iohk-module` itself, and that’s why the patch is applied twice? But the log only mentions the patch once…

**Comment by nomeata** [comment]
It seems to pull in a version of `hsc2hs` that is too new (or use a too old `ghc`).
```
building '/nix/store/qvl8lahpsn70fdyflg599fgvmb6drj7y-hsc2hs-0.68.4-exe-hsc2hs.drv'...
unpacking sources
unpacking source archive /nix/store/i1hg8a1qb1xg11br3czp0d2nn3rs98db-hsc2hs-0.68.4.tar.gz
source root is hsc2hs-0.68.4
setting SOURCE_DATE_EPOCH to timestamp 1537741356 of file hsc2hs-0.68.4/UtilsCodegen.hs
patching sources
configuring
Configure flags:
--prefix=/nix/store/hlaz9l6sx08y9aj4hxn0xms7xpsapmsm-hsc2hs-0.68.4-exe-hsc2hs exe:hsc2hs --package-db=clear --package-db=/nix/store/m99ahl8rxb3vkn3fwjqwl27kh2s463iz-hsc2hs-0.68.4-exe-hsc2hs-config/package.conf.d --flags=-in-ghc-tree --with-ghc=ghc --with-ghc-pkg=ghc-pkg --with-hsc2hs=hsc2hs --with-gcc=cc --with-ld=ld --with-ar=ar --with-strip=strip --enable-executable-stripping --enable-library-stripping --enable-split-sections
Configuring executable 'hsc2hs' for hsc2hs-0.68.4..
Setup: Encountered missing dependencies:
base >=4.12 && <5

builder for '/nix/store/qvl8lahpsn70fdyflg599fgvmb6drj7y-hsc2hs-0.68.4-exe-hsc2hs.drv' failed with exit code 1
```

My Cabal-plan generated package plan specifies `ghc844` (not entirely intentional). Maybe I should fix that. I see that cardano-chain uses ghc-8.6.3. I should try that. But I get a very big warning
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
************************************ WARNING ***********************************
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

         You are using GHC 8.6.3.  This version is known to
         be busted on windows!  See GHC issue #16057.  Make
         sure you revert commit
           ghc:ed86e3b531322f74d2c2d00d7ff8662b08fabde6
         before using GHC 8.6.3 in any form on windows.

         --
         https://ghc.haskell.org/trac/ghc/ticket/16057

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
************************************ WARNING ***********************************
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by angerman** [comment]
@nomeata right, you get that warning. However the ghc-8.6.3 that we use (and that's in iohk-nix) *is* sufficiently patched for windows. The warning is just there for informational purposes.

**Comment by angerman** [comment]
Of note: since da7c1edc31d24ff4a211b7dc2361c71af7c3bda4, `th-packages` is not required anymore.

**Comment by nomeata** [comment]
Ok, I regenerated the plan from a fresh `cabal new-build` plan using ghc-8.6.3. Curiously, now the right flags for `transformers-compat` are included in the generated `plan.nix`.

And now it works! Great :-)
