### ISSUE TITLE
nix-tools.release-nix: better support for disabling jobs

### ISSUE THREAD

**Issue by jbgi** [input-output-hk/iohk-nix#46]
(context: https://github.com/input-output-hk/cardano-chain/pull/366)

**Comment by angerman** [comment]
@jbgi any syntax you envision how to do this better?

**Comment by jbgi** [comment]
@angerman I was thinking of an `excludedJobs` attribute, eg.:
```nix
nix-tools.release-nix {
  package-set-path = ./.;
  packages = [ "iohk-monitoring" ];
  excludedJobs = [ "nix-tools.tests.iohk-monitoring.tests.x86_64-darwin" ];
  required-name = "iohk-monitoring-required-checks";
  required-targets = jobs: [
    jobs.nix-tools.tests.iohk-monitoring.tests.x86_64-linux
    jobs.nix-tools.exes.iohk-monitoring.x86_64-linux
  ];
}
```

**Comment by angerman** [comment]
@jbgi I'd prefer something more descriptive: `broken-jobs`? But what's wrong with 
```
  required-targets = jobs: [
    # the following is disabled due to ...
    # jobs.nix-tools.tests.iohk-monitoring.tests.x86_64-linux
    jobs.nix-tools.exes.iohk-monitoring.x86_64-linux
  ];
```

**Comment by jbgi** [comment]
@angerman I think commenting out in `required-targets` does not avoid hydra still building it.
I like `broken-jobs`.

**Comment by angerman** [comment]
@jbgi did you end up implementing this somewhere? I think(?) I've seen this in some project, but lost track of which it was. Maybe I've been hallucinating as well :-)

**Comment by jbgi** [comment]
@angerman yes, but in a rather clunky way:
https://github.com/input-output-hk/iohk-monitoring-framework/blob/develop/release.nix#L3
