### ISSUE TITLE
blst lib found by cardano-api, not by cardano-node 

### ISSUE THREAD

**Issue by waalge** [input-output-hk/iohk-nix#546]
Id like to the run a node with the latest plutus builtins.
I dont intimately understand the dependency structure her but  from what i can tell, cardano-api is fine with relaxing the plutus constraints
https://github.com/waalge/cardano-api/commit/5167ab67b9ce31f2ef924432eca8ee02744c2e18
but no such luck with the cardano node 
https://github.com/input-output-hk/cardano-node/commit/abe04455674b69796a76f8ec67af6a232b8f9e17

Its been a long fight to this point. I had a similar issue that was resolved with a pointer that something was up with the iohknix dep. https://github.com/input-output-hk/cardano-haskell-packages/issues/334
And there is an ominous note in the node flake 
https://github.com/waalge/cardano-node/blob/af43012b81f0c0370dc136298d641c7228bbb58f/flake.nix#L105
suggesting this is delicate. 

would really appreciate some pointers as to nix cannot see blst here. The nix code is involved to say the least

**Comment by waalge** [comment]
node seems to organise its patching in a different way 
https://github.com/input-output-hk/cardano-node/blob/5dc08704b06abaa0724f3d0c40dc8fddfee4b697/nix/haskell.nix#L81
:shrug: 
I dont know how you're supposed to navigate around this

**Comment by james-iohk** [comment]
@waalge Have you tried adding `pkgconfig-depends: libblst` to the cabal file?  Also try pinning `cardano-crypto-class == 2.1.1.0`

**Comment by waalge** [comment]
@james-iohk Thanks for comment. I resolved this by adding the blst in the line linked above. 
This worked, but it was a short victory cos i was unable to spin up a working cluster and or get the cli to handle conway txs. Ive given up for now.

**Comment by james-iohk** [comment]
@waalge I've been trying something similar. Did manage to spin up a local cluster in Conway era but there are some undefined parts of the Conway txbody in ledger code preventing tx build (using cardano-api). The core devs are still in the process of integrating so I have parked this for now.

**Comment by waalge** [comment]
> undefined parts of the Conway txbody in ledger
yeah - from I what inferred from comments and the state of code is there was a reason this had been left not done.

I tried running in babbage era, but the cluster wouldnt get out of the 0th slot. No obvious error messages pointing at why. Tried a few things, threw in the towel

**Comment by james-iohk** [comment]
How are you starting the local testnet?

There is `cardano-testnet`, which you can see example usage of in its tests [here](https://github.com/input-output-hk/cardano-node/blob/c3119ecd472807447472b51e337b3dad37c40a00/cardano-testnet/test/cardano-testnet-test/Cardano/Testnet/Test/Cli/Babbage/LeadershipSchedule.hs#L61).
You can look at [antaeus](https://github.com/input-output-hk/antaeus), which also uses `cardano-testnet` for starting networks with protocol versions 6 (Alonzo), 7 and 8 (Babbage), and there's a PR for 9 (Conway) but it's not ready yet.

`cardano-node-tests` also run in local environments, their scripts can be found in https://github.com/input-output-hk/cardano-node-tests/tree/master/cardano_node_tests/cluster_scripts
