### ISSUE TITLE
Update default pin to 19.03

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/iohk-nix#62]
It's out now.

Not sure what the blockers are here - do we need to still use our fork and make a new patched branch, or is enough stuff upstream now?

**Comment by angerman** [comment]
I believe not enough will be upstream, and I would hope they didn't break any cross logic. This probably needs a day or two to be investigated.  What would be the benefits for us to move to 19.03?

@disassembler thoughts?

**Comment by michaelpj** [comment]
Newer stuff, plus it's just less painful to do these kinds of upgrades as they come.

(I turns out that the thing which I actually want -- a newer version of Agda -- isn't in there, but it seems like a good idea anyway.)

**Comment by michaelpj** [comment]
It looks like 18.09 may not work completely on recent versions of MacOS any more, so upgrading is a bit more of a priority for us as we have several Mac users.

https://github.com/input-output-hk/plutus/issues/1018
