### ISSUE TITLE
haddock postInstall hook breaks justStaticExecutables

### ISSUE THREAD

**Issue by cleverca22** [input-output-hk/iohk-nix#69]
if you run `justStaticExecutables` on something that the `haddock-hydra.nix` overlay has touched, then the build will fail:
```
Installing library in /nix/store/1my1336f7g8fz4yvkwq0pmzrbh62lfj2-meadow-0.1.0.0/lib/ghc-8.6.4/x86_64-linux-ghc-8.6.4/meadow-0.1.0.0-IpbvTtm5O0h7URJLPn0lq
Installing executable meadow-exe in /nix/store/1my1336f7g8fz4yvkwq0pmzrbh62lfj2-meadow-0.1.0.0/bin
Warning: The directory
/nix/store/1my1336f7g8fz4yvkwq0pmzrbh62lfj2-meadow-0.1.0.0/bin is not in the
system search path.
Registering library for meadow-0.1.0.0..
mkdir: cannot create directory ‘/nix-support’: Permission denied
```
thats due to `justStaticExecutables` removing `out` from `outputs` and now `$out` is unset

https://github.com/input-output-hk/iohk-nix/blob/master/overlays/haddock-hydra.nix

will need to be modified to somehow detect that `justStaticExecutables` has been ran and stop trying to create docs
one option is to just test if `$doc` is set

a temporarily work-around is to either:
`meadow-static = static (pkgs.haskell.lib.overrideCabal haskellPackages.meadow (drv: { postInstall = ""; }));`
or to exclude the package from getting haddock at the `filterOverrides = { haddock = localButNot` area

**Comment by michaelpj** [comment]
Not sure how many people are using the haddock hydra overlay apart from Plutus, but tbh I don't think we really need it. We do build the Haddock, but we glue it together into a combined thing at the end and that's the artifact we use.

So we could potentially just drop this.
